language: objective-c
xcode_workspace: SwiftyConcuriOSExample/SwiftyConcuriOSExample.xcworkspace
xcode_scheme: SwiftyConcurExample
podfile: SwiftyConcuriOSExample/Podfile
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
cache: cocoapods
script: xcodebuild -workspace SwiftyConcuriOSExample/SwiftyConcuriOSExample.xcworkspace -scheme SwiftyConcurExample -sdk iphonesimulator9.3 build test
