platform :ios, '8.0'
use_frameworks!

target 'SwiftyConcuriOSExample' do
  pod 'SwiftyConcur', :git => 'https://github.com/concurlabs/SwiftyConcur.git', :tag => '0.0.6'
end

target 'SwiftyConcuriOSExampleTests' do
  pod 'SwiftyConcur', :git => 'https://github.com/concurlabs/SwiftyConcur.git', :tag => '0.0.6'
  pod 'OHHTTPStubs'
end
